[workspace]

members = [
  "cli",
  "common",
  "conductor",
  "conductor_api",
  "core_api_c_binding",
  "core",
  "dna_c_binding",
  "hdk-rust",
  "net",
  "net_connection",
  "net_ipc",
  "nodejs_waiter",
  "sodium",
  "hc_dpki",
  "test_bin",
]
exclude = [
  "test_utils",
  "app_spec",
  "nodejs_conductor/native",
  "rust_sodium-sys",
  "zmq-sys",
]

[patch.crates-io]
rust_sodium-sys = { path = "./rust_sodium-sys" }
zmq-sys = { path = "./zmq-sys" }
